version: '3'

services:
  instancerapi:
    image: instancerapi
    build: .
    volumes:
    - ./chal:/app/chal:ro
    privileged: true
    environment:
    - PORT=8000
    - TOKEN=testtoken
    - DBNAME=instance.db
    - MINPORT=30000
    - MAXPORT=31000
    - VALIDITY=3m
    - FLAGPREFIX=TSC
    - FLAGMSG=testflag
    - PREFIX=29
    - SUBNETPOOL=10.200.0.0/16
    - CHALDIR=chal
    - BASESCHEME=http
    - BASEHOST=
    - PROXYMODE=true
    - NCMODE=false
    ports:
    - 8000:8000
    #- 30000-31000:30000-31000
